
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: admin-pro-part-postgis
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_pro_part_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - admin_pro_part_postgis_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - admin-pro-part-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  admin-panel-db:
    image: postgres:15
    container_name: admin-pro-part-postgres
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: admin_panel
    volumes:
      - admin_pro_part_db_data:/var/lib/postgresql/data
    networks:
      - admin-pro-part-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: admin-pro-part-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --appendonly yes
    volumes:
      - admin_pro_part_redis_data:/data
    networks:
      - admin-pro-part-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncommnet для запуску backend у Docker
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: for-you-real-estate-backend
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   networks:
  #     - for-you-network

volumes:
  admin_pro_part_postgis_data:
    driver: local
  admin_pro_part_redis_data:
    driver: local
  admin_pro_part_db_data:
    driver: local

networks:
  admin-pro-part-network:
    driver: bridge

