services:
  admin-panel-db:
    image: postgres:15-alpine
    container_name: admin-panel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: admin_panel_propart
    ports:
      - "5436:5432"
    volumes:
      - admin-panel-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  admin-panel-db-data:

